/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoNota1;


import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import tools.CaixaDeDialogo;

/**
 *
 * @author vitoria.schneider
 */
public class TelaContas extends javax.swing.JFrame {
    
    Conta objetoConta;
    Conta objetoConta2;
    DefaultComboBoxModel modelConta;
    ArrayList<Conta> listaContas;
    
    
    public TelaContas() {
        initComponents();
        
        ArrayList<Conta> listaContas = new ArrayList<>();
        
        Conta objConta = new Conta();
        objConta.setTitular("vitoria");
        objConta.setNumConta(111);
        objConta.setSaldoConta(300);        
        objConta.setLimitCheque(1000);
        
        listaContas.add(objConta);
        
        objConta = new Conta();
        objConta.setTitular("Leila Lopes");
        objConta.setNumConta(222);
        objConta.setSaldoConta(900);
        objConta.setLimitCheque(2000);
        
        listaContas.add(objConta);
        
        modelConta = new DefaultComboBoxModel();
        for(Conta objeto: listaContas){
            modelConta.addElement(objeto);
        }
        cmb1.setModel(modelConta);
        
        modelConta = new DefaultComboBoxModel();
        for(Conta objeto: listaContas){
            modelConta.addElement(objeto);
        }
        cmb2.setModel(modelConta);
        
    }
    
    private void atulizarSaldos(){
        lblSaldo.setText("Saldo : " +objetoConta.getSaldoConta());
        TxtConta1.setText("");
        
        lblSaldo2.setText("Saldo : " +objetoConta2.getSaldoConta());
        TxtConta2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeConta1 = new javax.swing.JLabel();
        lblNomeConta2 = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblNumero2 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblSaldo2 = new javax.swing.JLabel();
        btnSacar = new javax.swing.JButton();
        btnDepositar = new javax.swing.JButton();
        btnTransferir = new javax.swing.JButton();
        TxtConta1 = new javax.swing.JTextField();
        TxtConta2 = new javax.swing.JTextField();
        btnSacar2 = new javax.swing.JButton();
        btnDepositar2 = new javax.swing.JButton();
        btnTransferir2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblChequeEspecial = new javax.swing.JLabel();
        lblChequeEspecial2 = new javax.swing.JLabel();
        cmb1 = new javax.swing.JComboBox<>();
        cmb2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNomeConta1.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        lblNomeConta1.setText("CONTA 1");

        lblNomeConta2.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        lblNomeConta2.setText("CONTA 2");

        lblNumero.setText("número conta:");

        lblNumero2.setText("número conta:");

        lblSaldo.setText("saldo");

        lblSaldo2.setText("saldo");

        btnSacar.setText("sacar");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        btnDepositar.setText("depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnTransferir.setText("transferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });

        TxtConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtConta1ActionPerformed(evt);
            }
        });

        TxtConta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtConta2ActionPerformed(evt);
            }
        });

        btnSacar2.setText("sacar");
        btnSacar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacar2ActionPerformed(evt);
            }
        });

        btnDepositar2.setText("depositar");
        btnDepositar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositar2ActionPerformed(evt);
            }
        });

        btnTransferir2.setText("transferir");
        btnTransferir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferir2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-itau-256.png"))); // NOI18N

        lblChequeEspecial.setText("cheque especial");

        lblChequeEspecial2.setText("cheque especial");

        cmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1ActionPerformed(evt);
            }
        });

        cmb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblChequeEspecial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtConta1)
                    .addComponent(btnDepositar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(lblNomeConta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSacar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransferir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(235, 235, 235)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSacar2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDepositar2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTransferir2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNomeConta2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmb2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumero2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSaldo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblChequeEspecial2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(TxtConta2))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeConta2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeConta1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(cmb1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lblNumero2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChequeEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChequeEspecial2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtConta1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtConta2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacar)
                    .addComponent(btnSacar2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(btnDepositar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDepositar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransferir)
                    .addComponent(btnTransferir2))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        
        try{
            boolean resposta = CaixaDeDialogo.obterinstancia().pedirConfirmacao("deseja mesmo sacar?", "confirmacao", 'p');
            if(resposta ==true){
            Double valorSaque =Double.parseDouble(TxtConta1.getText());
        
            if(objetoConta.sacar(valorSaque)){
            atulizarSaldos();
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("saldo insuficiente", 'e');
            }
        }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("NAO", 'e');
            }
        
        }catch(Exception ex){
                CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage(),'e');
                }
        
    }//GEN-LAST:event_btnSacarActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        try{
        Double valorDeposito = Double.parseDouble(TxtConta1.getText());
        objetoConta.depositar(valorDeposito);
        atulizarSaldos();
        }catch(Exception ex){
                CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage(),'e');
                }
        
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        try{
        Double valorTransferencia = Double.parseDouble(TxtConta1.getText());

        objetoConta.transferir(valorTransferencia, objetoConta2);
        atulizarSaldos();
        
        }catch(Exception ex){
                CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage(),'e');
                }
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void TxtConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtConta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtConta1ActionPerformed

    private void TxtConta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtConta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtConta2ActionPerformed

    private void btnSacar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacar2ActionPerformed
        try{
            
        Double valorSaque =Double.parseDouble(TxtConta2.getText());
        
        if(objetoConta2.sacar(valorSaque)){
            atulizarSaldos();
        }
        }catch(Exception ex){
                CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage(),'e');
                }
    }//GEN-LAST:event_btnSacar2ActionPerformed

    private void btnDepositar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositar2ActionPerformed
       try{
        Double valorDeposito = Double.parseDouble(TxtConta2.getText());
        objetoConta2.depositar(valorDeposito);
        atulizarSaldos();
        
       }catch(Exception ex){
                CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage(),'e');
                }
       
    }//GEN-LAST:event_btnDepositar2ActionPerformed

    private void btnTransferir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferir2ActionPerformed
        try{
        Double valorTransferencia = Double.parseDouble(TxtConta2.getText());

        objetoConta2.transferir(valorTransferencia, objetoConta);
        atulizarSaldos();
        
        }catch(Exception ex){
                CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage(),'e');
                }
    }//GEN-LAST:event_btnTransferir2ActionPerformed

    private void cmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1ActionPerformed
        objetoConta = (Conta) cmb1.getSelectedItem();
        
        lblNomeConta1.setText("Titular : " + objetoConta.getTitular());
        
        lblNumero.setText("Número Conta : " +objetoConta.getNumConta());
        
        lblSaldo.setText("Saldo : " +objetoConta.getSaldoConta());
        
        lblChequeEspecial.setText("cheque especial " +objetoConta.getLimitCheque());
        
        TxtConta1.setText("");
       
        

    }//GEN-LAST:event_cmb1ActionPerformed

    private void cmb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb2ActionPerformed
        objetoConta2 = (Conta) cmb2.getSelectedItem();
        
        lblNomeConta2.setText("Titular : " + objetoConta2.getTitular());
        
        lblNumero2.setText("Número Conta : " +objetoConta2.getNumConta());
        
        lblSaldo2.setText("Saldo : " +objetoConta2.getSaldoConta());
        
        lblChequeEspecial2.setText("cheque especial " +objetoConta2.getLimitCheque());
        
        TxtConta2.setText("");
        

    }//GEN-LAST:event_cmb2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtConta1;
    private javax.swing.JTextField TxtConta2;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnDepositar2;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton btnSacar2;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JButton btnTransferir2;
    private javax.swing.JComboBox<String> cmb1;
    private javax.swing.JComboBox<String> cmb2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblChequeEspecial;
    private javax.swing.JLabel lblChequeEspecial2;
    private javax.swing.JLabel lblNomeConta1;
    private javax.swing.JLabel lblNomeConta2;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumero2;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldo2;
    // End of variables declaration//GEN-END:variables
}
